import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import warnings

from .style import UNIFORM_BLUE, PALE_PINK

warnings.simplefilter(
    action="ignore",
    category=FutureWarning
)

warnings.simplefilter(
    action="ignore",
    category=UserWarning
)

#--- Function : plot_monte_carlo ---
def plot_monte_carlo(
    mc_results,
    bins=50,
    figsize=(12, 8),
    sensitivity_top_n=10,
    title=None
):
    """
    Visualize Monte Carlo simulation results through outcome
    distribution, uncertainty interval, convergence analysis,
    and sensitivity assessment.

    Parameters
    ----------
    mc_results : dict
        Output dictionary generated by monte_carlo_simulation().
        Must contain:
        - simulation_results : pandas.DataFrame
        - summary : pandas.Series
        - sensitivity_analysis : pandas.Series or None

    bins : int, default=50
        Number of histogram bins.

    figsize : tuple, default=(12, 8)
        Figure size.

    sensitivity_top_n : int, default=10
        Number of most influential variables displayed.

    title : str, optional
        Figure title.

    Returns
    -------
    matplotlib.figure.Figure
        Generated figure.
    """

    # Validate inputs

    if not isinstance(mc_results, dict):
        raise ValueError(
            "'mc_results' must be a dictionary generated by monte_carlo_simulation()."
        )

    required_keys = [
        "simulation_results",
        "summary",
        "sensitivity_analysis"
    ]

    missing_keys = [
        key for key in required_keys
        if key not in mc_results
    ]

    if missing_keys:
        raise ValueError(
            f"Missing key(s) in Monte Carlo results: {missing_keys}"
        )

    simulation_df = mc_results["simulation_results"]
    summary = mc_results["summary"]
    sensitivity = mc_results["sensitivity_analysis"]

    if "Result" not in simulation_df.columns:
        raise ValueError(
            "'simulation_results' must contain a 'Result' column."
        )

    results = simulation_df["Result"].dropna()

    if len(results) == 0:
        raise ValueError(
            "No valid simulation results available."
        )

    if not isinstance(bins, int) or bins < 1:
        raise ValueError(
            "'bins' must be a positive integer."
        )

    if not isinstance(sensitivity_top_n, int) or sensitivity_top_n < 1:
        raise ValueError(
            "'sensitivity_top_n' must be a positive integer."
        )

    # Create figure

    fig, axes = plt.subplots(
        2,
        2,
        figsize=figsize
    )

    # Distribution

    axes[0, 0].hist(
        results,
        bins=bins,
        color=UNIFORM_BLUE,
        alpha=0.7,
        density=True
    )

    axes[0, 0].axvline(
        summary["Mean"],
        color=UNIFORM_BLUE,
        linestyle="--",
        label=f"Mean: {summary['Mean']:.2f}"
    )

    axes[0, 0].axvline(
        summary["Median"],
        color=PALE_PINK,
        linestyle="-",
        label=f"Median: {summary['Median']:.2f}"
    )

    axes[0, 0].axvspan(
        summary["P5"],
        summary["P95"],
        alpha=0.25,
        label="P5-P95 interval"
    )

    axes[0, 0].set_title(
        "Monte Carlo Outcome Distribution"
    )

    axes[0, 0].set_xlabel(
        "Simulated Result"
    )

    axes[0, 0].set_ylabel(
        "Density"
    )

    axes[0, 0].legend()

    # Uncertainty range

    axes[0, 1].boxplot(
        results,
        vert=False
    )

    axes[0, 1].axvline(
        summary["P5"],
        linestyle="--"
    )

    axes[0, 1].axvline(
        summary["P95"],
        linestyle="--"
    )

    axes[0, 1].set_title(
        "Simulation Uncertainty Range"
    )

    axes[0, 1].set_xlabel(
        "Result"
    )

    # Convergence

    cumulative_mean = (
        results
        .expanding()
        .mean()
    )

    axes[1, 0].plot(
        cumulative_mean,
        color=UNIFORM_BLUE
    )

    axes[1, 0].axhline(
        summary["Mean"],
        linestyle="--",
        label="Final mean"
    )

    axes[1, 0].set_title(
        "Monte Carlo Convergence"
    )

    axes[1, 0].set_xlabel(
        "Simulation Number"
    )

    axes[1, 0].set_ylabel(
        "Cumulative Mean"
    )

    axes[1, 0].legend()

    # Sensitivity analysis

    if sensitivity is not None:

        sensitivity_plot = (
            sensitivity
            .head(sensitivity_top_n)
            .sort_values()
        )

        sensitivity_plot.plot.barh(
            ax=axes[1, 1],
            color=UNIFORM_BLUE
        )

        axes[1, 1].set_title(
            "Input Sensitivity Analysis"
        )

        axes[1, 1].set_xlabel(
            "Correlation with Result"
        )

    else:

        axes[1, 1].text(
            0.5,
            0.5,
            "Sensitivity analysis unavailable",
            ha="center",
            va="center"
        )

        axes[1, 1].set_axis_off()

    fig.suptitle(
        title or "Monte Carlo Simulation Analysis",
        fontsize=14,
        fontweight="bold"
    )

    plt.tight_layout(
        rect=[0, 0, 1, 0.95]
    )

    return fig
